// This file is automatically generated by CMake. Do not edit.
namespace GridForcePlugin {
namespace CommonGridForceKernelSources {

const char* gridForceSource = R"__kernel(
// Common kernel code here if needed
)__kernel";

}
}
