# Create the kernel source file.
FILE(WRITE "${OUTPUT_FILE}" "// This file is automatically generated by CMake. Do not edit.\n")
FILE(APPEND "${OUTPUT_FILE}" "namespace GridForcePlugin {\n")
FILE(APPEND "${OUTPUT_FILE}" "namespace CommonGridForceKernelSources {\n\n")

# Insert headers for grid force kernels
FILE(APPEND "${OUTPUT_FILE}" "const char* gridForceSource = R\"__kernel(\n")
FILE(APPEND "${OUTPUT_FILE}" "real3 make_real3(real x, real y, real z) {\n")
FILE(APPEND "${OUTPUT_FILE}" "    real3 v;\n")
FILE(APPEND "${OUTPUT_FILE}" "    v.x = x;\n")
FILE(APPEND "${OUTPUT_FILE}" "    v.y = y;\n")
FILE(APPEND "${OUTPUT_FILE}" "    v.z = z;\n")
FILE(APPEND "${OUTPUT_FILE}" "    return v;\n")
FILE(APPEND "${OUTPUT_FILE}" "}\n")
FILE(APPEND "${OUTPUT_FILE}" "\n")
FILE(APPEND "${OUTPUT_FILE}" ")__kernel\";\n\n")

FILE(APPEND "${OUTPUT_FILE}" "}\n")
FILE(APPEND "${OUTPUT_FILE}" "}\n")
