# Create the kernel source file.
FILE(WRITE "${OUTPUT_FILE}" "// This file is automatically generated by CMake. Do not edit.\n")
FILE(APPEND "${OUTPUT_FILE}" "namespace GridForcePlugin {\n")
FILE(APPEND "${OUTPUT_FILE}" "namespace CommonGridForceKernelSources {\n\n")

# Read and embed the gridForce.cc kernel source
FILE(READ "${INPUT_DIR}/gridForce.cc" GRID_FORCE_SOURCE)
FILE(APPEND "${OUTPUT_FILE}" "const char* gridForceSource = R\"__kernel(\n")
FILE(APPEND "${OUTPUT_FILE}" "${GRID_FORCE_SOURCE}")
FILE(APPEND "${OUTPUT_FILE}" ")__kernel\";\n\n")

FILE(APPEND "${OUTPUT_FILE}" "}\n")
FILE(APPEND "${OUTPUT_FILE}" "}\n")
