{% set name = "openmm-gridforce" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../..

build:
  number: 0
  skip: True  # [win]
  missing_dso_whitelist:
    - '*/libgcc_s.so.1'

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig >=4
    - make  # [unix]
  host:
    - python >=3.10
    - pip
    - openmm >=8.0
  run:
    - python >=3.10
    - openmm >=8.0
    - {{ pin_compatible('__glibc', max_pin='x.x') }}  # [linux]

test:
  requires:
    - pytest
  source_files:
    - python/tests
    - python/grids
    - python/prmtopcrd
  imports:
    - gridforceplugin
  commands:
    - python -c "import gridforceplugin; import openmm as mm; [print(mm.Platform.getPlatform(i).getName()) for i in range(mm.Platform.getNumPlatforms())]"

about:
  home: https://github.com/jimtufts/openmmgridforce
  license: MIT
  license_file: LICENSE
  summary: OpenMM plugin for grid-based forces
  description: |
    GridForce plugin for OpenMM that enables grid-based force calculations.

extra:
  recipe-maintainers:
    - jimtufts
