/* Auto-generated GBSA chain rule kernels */
/* Generated by generate_gbsa_chain_rule.py */

#ifndef GBSA_CHAIN_RULE_CUH
#define GBSA_CHAIN_RULE_CUH

#include <cmath>


/**
 * Accumulate dE/dR_born for each atom.
 * This must be called after computeGBEnergy to collect derivatives.
 */
extern "C" __global__ void accumulateBornRadiiDerivatives(
    const float4* __restrict__ posq,
    const int* __restrict__ particleIndices,
    const float* __restrict__ charges,
    const float* __restrict__ bornRadii,
    const int* __restrict__ exclusionAtoms,
    const int* __restrict__ exclusionStart,
    const int* __restrict__ groupStart,
    int numGroups,
    int templateNumAtoms,
    float prefactor,
    float* __restrict__ dE_dR  // Output: dE/dR_born for each atom
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    // Determine group
    int groupIdx = 0;
    int atomInGroup = idx;
    int groupStartIdx = 0;
    int groupEndIdx = 0;

    for (int g = 0; g < numGroups; g++) {
        groupStartIdx = groupStart[g];
        groupEndIdx = groupStart[g + 1];
        if (idx >= groupStartIdx && idx < groupEndIdx) {
            groupIdx = g;
            atomInGroup = idx - groupStartIdx;
            break;
        }
    }

    if (idx >= groupEndIdx) return;

    int particleIdx_i = particleIndices[idx];
    int templateIdx_i = atomInGroup % templateNumAtoms;

    float4 pos_i = posq[particleIdx_i];
    float q_i = charges[templateIdx_i];
    float R_i = bornRadii[idx];

    int exclStart = exclusionStart[templateIdx_i];
    int exclEnd = exclusionStart[templateIdx_i + 1];

    // Self energy derivative: dE_self/dR_i = -0.5 * prefactor * q_i^2 / R_i^2
    float dE_dRi = -0.5f * prefactor * q_i * q_i / (R_i * R_i);

    // Pairwise contributions
    int groupSize = groupEndIdx - groupStartIdx;
    for (int jLocal = 0; jLocal < groupSize; jLocal++) {
        if (jLocal == atomInGroup) continue;

        int j = groupStartIdx + jLocal;
        int templateIdx_j = jLocal % templateNumAtoms;

        // Check exclusions
        bool excluded = false;
        for (int e = exclStart; e < exclEnd; e++) {
            if (exclusionAtoms[e] == templateIdx_j) {
                excluded = true;
                break;
            }
        }
        if (excluded) continue;

        int particleIdx_j = particleIndices[j];
        float4 pos_j = posq[particleIdx_j];
        float q_j = charges[templateIdx_j];
        float R_j = bornRadii[j];

        float dx = pos_j.x - pos_i.x;
        float dy = pos_j.y - pos_i.y;
        float dz = pos_j.z - pos_i.z;
        float r2 = dx*dx + dy*dy + dz*dz;

        // f_gb computation
        float RiRj = R_i * R_j;
        float expArg = -r2 / (4.0f * RiRj);
        float expTerm = expf(expArg);
        float fgb2 = r2 + RiRj * expTerm;
        float fgb = sqrtf(fgb2);

        // d(fgb^2)/dR_i = R_j * expTerm * (1 + r2/(4*R_i^2*R_j))
        //               = R_j * expTerm + 0.25 * expTerm * r2 / R_i
        float dfgb2_dRi = R_j * expTerm + 0.25f * expTerm * r2 / R_i;
        float dfgb_dRi = dfgb2_dRi / (2.0f * fgb);

        // dE_pair/dR_i = -prefactor * q_i * q_j * dfgb_dRi / fgb^2
        float dE_pair_dRi = -prefactor * q_i * q_j * dfgb_dRi / fgb2;

        // Count each pair once (j>i contribution doubled)
        dE_dRi += 0.5f * dE_pair_dRi;  // Half because we count both i<j and i>j
    }

    dE_dR[idx] = dE_dRi;
}


/**
 * Compute forces from HCT chain rule through Born radii.
 * Must be called after accumulateBornRadiiDerivatives.
 */
extern "C" __global__ void computeHCTChainRuleForces(
    const float4* __restrict__ posq,
    const int* __restrict__ particleIndices,
    const float* __restrict__ radii,
    const float* __restrict__ scaleFactors,
    const float* __restrict__ bornRadii,
    const float* __restrict__ hctReceptor,
    const float* __restrict__ hctLigand,
    const float* __restrict__ dE_dR,
    const int* __restrict__ exclusionAtoms,
    const int* __restrict__ exclusionStart,
    const int* __restrict__ groupStart,
    int numGroups,
    int templateNumAtoms,
    unsigned long long* __restrict__ forceBuffer,
    int paddedNumAtoms
) {
    int idx = blockIdx.x * blockDim.x + threadIdx.x;

    // Determine group
    int groupIdx = 0;
    int atomInGroup = idx;
    int groupStartIdx = 0;
    int groupEndIdx = 0;

    for (int g = 0; g < numGroups; g++) {
        groupStartIdx = groupStart[g];
        groupEndIdx = groupStart[g + 1];
        if (idx >= groupStartIdx && idx < groupEndIdx) {
            groupIdx = g;
            atomInGroup = idx - groupStartIdx;
            break;
        }
    }

    if (idx >= groupEndIdx) return;

    int particleIdx_i = particleIndices[idx];
    int templateIdx_i = atomInGroup % templateNumAtoms;

    float4 pos_i = posq[particleIdx_i];
    float R_i = radii[templateIdx_i];
    float R_i_off = R_i - 0.009f;  // DIELECTRIC_OFFSET
    float R_born_i = bornRadii[idx];

    // Compute dR_born/dpsi using OBC-II derivative
    float hctTotal_i = hctReceptor[idx] + hctLigand[idx];
    float psi_i = 0.5f * R_i_off * hctTotal_i;

    // OBC-II: tanh_arg = alpha*psi - beta*psi^2 + gamma*psi^3
    const float alpha = 1.0f;
    const float beta = 0.8f;
    const float gamma = 4.85f;

    float psi2 = psi_i * psi_i;
    float psi3 = psi2 * psi_i;
    float tanh_arg = alpha * psi_i - beta * psi2 + gamma * psi3;
    float t = tanhf(tanh_arg);
    float sech2 = 1.0f - t * t;
    float darg_dpsi = alpha - 2.0f * beta * psi_i + 3.0f * gamma * psi2;

    // dR_born/dpsi = R_born^2 * sech^2 * darg/dpsi / R_i
    float dR_dpsi_i = R_born_i * R_born_i * sech2 * darg_dpsi / R_i;

    // dE/dHCT_i = dE/dR_i * dR_i/dpsi_i * dpsi_i/dHCT_i
    // where dpsi/dHCT = 0.5 * R_off
    float dE_dHCT_i = dE_dR[idx] * dR_dpsi_i * 0.5f * R_i_off;

    int exclStart = exclusionStart[templateIdx_i];
    int exclEnd = exclusionStart[templateIdx_i + 1];

    float3 force = make_float3(0.0f, 0.0f, 0.0f);

    // Force from ligand-ligand HCT derivatives
    int groupSize = groupEndIdx - groupStartIdx;
    for (int jLocal = 0; jLocal < groupSize; jLocal++) {
        if (jLocal == atomInGroup) continue;

        int j = groupStartIdx + jLocal;
        int templateIdx_j = jLocal % templateNumAtoms;

        // Check exclusions
        bool excluded = false;
        for (int e = exclStart; e < exclEnd; e++) {
            if (exclusionAtoms[e] == templateIdx_j) {
                excluded = true;
                break;
            }
        }
        if (excluded) continue;

        int particleIdx_j = particleIndices[j];
        float4 pos_j = posq[particleIdx_j];
        float R_j = radii[templateIdx_j];
        float R_j_off = R_j - 0.009f;
        float S_j = R_j_off * scaleFactors[templateIdx_j];

        float dx = pos_i.x - pos_j.x;
        float dy = pos_i.y - pos_j.y;
        float dz = pos_i.z - pos_j.z;
        float r2 = dx*dx + dy*dy + dz*dz;
        float r = sqrtf(r2);

        if (r < 1e-6f) continue;

        // Compute dHCT_i/dr for contribution of atom j to HCT of atom i
        float r_plus_Sj = r + S_j;
        if (R_i_off >= r_plus_Sj) continue;

        float r_minus_Sj = fabsf(r - S_j);

        // Determine case and compute derivative
        float dHCT_dr;

        if (R_i_off > r_minus_Sj) {
            // Case 1: l = 1/R_i (constant in r)
            float u = 1.0f / r_plus_Sj;
            float l = 1.0f / R_i_off;
            float u2 = u * u;
            float l2 = l * l;
            float S2 = S_j * S_j;
            float invr = 1.0f / r;
            float invr2 = invr * invr;

            // dHCT/dr for Case 1: l constant
            // d/dr [l - u + 0.25*r*(u² - l²) + 0.5/r*ln(u/l) + 0.25*S²/r*(l² - u²)]
            // = du/dr + 0.25*(u² - l²) + 0.25*r*2*u*du/dr
            //   - 0.5/r² * ln(u/l) + 0.5/r * (1/u)*du/dr
            //   - 0.25*S²/r² * (l² - u²) + 0.25*S²/r * (-2*u*du/dr)
            // where du/dr = -1/(r+S)² = -u²

            float du_dr = -u2;
            float ln_u_l = logf(u / l);

            dHCT_dr = -du_dr  // = u²
                    + 0.25f * (u2 - l2)
                    + 0.5f * r * u * du_dr  // = -0.5 * r * u³
                    - 0.5f * invr2 * ln_u_l
                    + 0.5f * invr * (-1.0f) * du_dr  // = 0.5/r * u²
                    - 0.25f * S2 * invr2 * (l2 - u2)
                    + 0.25f * S2 * invr * 2.0f * u * (-du_dr);  // = 0.5 * S²/r * u³
        } else {
            // Case 2: l = 1/(r-S) for r > S
            float rms = r - S_j;
            float l = 1.0f / rms;
            float u = 1.0f / r_plus_Sj;
            float l2 = l * l;
            float u2 = u * u;
            float S2 = S_j * S_j;
            float invr = 1.0f / r;
            float invr2 = invr * invr;

            // dl/dr = -1/(r-S)² = -l²
            // du/dr = -1/(r+S)² = -u²
            float dl_dr = -l2;
            float du_dr = -u2;
            float ln_u_l = logf(u / l);

            dHCT_dr = dl_dr - du_dr
                    + 0.25f * (u2 - l2)
                    + 0.5f * r * (u * du_dr - l * dl_dr)
                    - 0.5f * invr2 * ln_u_l
                    + 0.5f * invr * ((1.0f/u) * du_dr - (1.0f/l) * dl_dr)
                    - 0.25f * S2 * invr2 * (l2 - u2)
                    + 0.25f * S2 * invr * (2.0f * l * dl_dr - 2.0f * u * du_dr);
        }

        // Force contribution: F_i += -dE_dHCT_i * dHCT_i/dr * dr/dx_i
        // dr/dx_i = (x_i - x_j) / r = dx / r (for x component)
        float invr = 1.0f / r;
        float dE_dr_i = dE_dHCT_i * dHCT_dr;

        // This force acts on i due to HCT_i depending on position of j
        // F_i = -dE/dx_i = -dE/dr * dr/dx_i = -dE/dr * (x_i - x_j)/r
        force.x -= dE_dr_i * dx * invr;
        force.y -= dE_dr_i * dy * invr;
        force.z -= dE_dr_i * dz * invr;

        // Also need force on i from HCT_j depending on position of i
        // F_i += -dE_dHCT_j * dHCT_j/dr_ji * dr_ji/dx_i
        // dr_ji/dx_i = -(x_i - x_j)/r = -dx/r
        // So F_i += dE_dHCT_j * dHCT_j/dr * dx/r

        // Compute dE_dHCT_j
        float R_born_j = bornRadii[j];
        float hctTotal_j = hctReceptor[j] + hctLigand[j];
        float psi_j = 0.5f * R_j_off * hctTotal_j;
        float psi2_j = psi_j * psi_j;
        float psi3_j = psi2_j * psi_j;
        float tanh_arg_j = alpha * psi_j - beta * psi2_j + gamma * psi3_j;
        float t_j = tanhf(tanh_arg_j);
        float sech2_j = 1.0f - t_j * t_j;
        float darg_dpsi_j = alpha - 2.0f * beta * psi_j + 3.0f * gamma * psi2_j;
        float dR_dpsi_j = R_born_j * R_born_j * sech2_j * darg_dpsi_j / R_j;
        float dE_dHCT_j = dE_dR[j] * dR_dpsi_j * 0.5f * R_j_off;

        // Now compute dHCT_j/dr for contribution of atom i to HCT of atom j
        float S_i = R_i_off * scaleFactors[templateIdx_i];
        float r_plus_Si = r + S_i;
        if (R_j_off < r_plus_Si) {
            float r_minus_Si = fabsf(r - S_i);
            float dHCT_j_dr;

            if (R_j_off > r_minus_Si) {
                // Case 1 for j
                float u = 1.0f / r_plus_Si;
                float l = 1.0f / R_j_off;
                float u2 = u * u;
                float l2 = l * l;
                float S2 = S_i * S_i;
                float invr_loc = 1.0f / r;
                float invr2 = invr_loc * invr_loc;

                float du_dr = -u2;
                float ln_u_l = logf(u / l);

                dHCT_j_dr = -du_dr
                          + 0.25f * (u2 - l2)
                          + 0.5f * r * u * du_dr
                          - 0.5f * invr2 * ln_u_l
                          + 0.5f * invr_loc * (-1.0f) * du_dr
                          - 0.25f * S2 * invr2 * (l2 - u2)
                          + 0.25f * S2 * invr_loc * 2.0f * u * (-du_dr);
            } else {
                // Case 2 for j
                float rms = r - S_i;
                float l = 1.0f / rms;
                float u = 1.0f / r_plus_Si;
                float l2 = l * l;
                float u2 = u * u;
                float S2 = S_i * S_i;
                float invr_loc = 1.0f / r;
                float invr2 = invr_loc * invr_loc;

                float dl_dr = -l2;
                float du_dr = -u2;
                float ln_u_l = logf(u / l);

                dHCT_j_dr = dl_dr - du_dr
                          + 0.25f * (u2 - l2)
                          + 0.5f * r * (u * du_dr - l * dl_dr)
                          - 0.5f * invr2 * ln_u_l
                          + 0.5f * invr_loc * ((1.0f/u) * du_dr - (1.0f/l) * dl_dr)
                          - 0.25f * S2 * invr2 * (l2 - u2)
                          + 0.25f * S2 * invr_loc * (2.0f * l * dl_dr - 2.0f * u * du_dr);
            }

            // Force on i from HCT_j: F_i += dE_dHCT_j * dHCT_j/dr * dx/r
            float dE_dr_j = dE_dHCT_j * dHCT_j_dr;
            force.x += dE_dr_j * dx * invr;
            force.y += dE_dr_j * dy * invr;
            force.z += dE_dr_j * dz * invr;
        }
    }

    // Accumulate force
    atomicAdd(&forceBuffer[particleIdx_i], static_cast<unsigned long long>((long long)(force.x * 0x100000000)));
    atomicAdd(&forceBuffer[particleIdx_i + paddedNumAtoms], static_cast<unsigned long long>((long long)(force.y * 0x100000000)));
    atomicAdd(&forceBuffer[particleIdx_i + 2*paddedNumAtoms], static_cast<unsigned long long>((long long)(force.z * 0x100000000)));
}

#endif // GBSA_CHAIN_RULE_CUH
