/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_hct_cuda_derivatives.py
 *
 * HCT (Hawkins-Cramer-Truhlar) analytical r-derivatives for GBSA grid generation.
 * Computes the 7 r-derivatives (I0 through I6) of the HCT integral.
 *
 * To get the 27 Cartesian derivatives needed for triquintic interpolation,
 * use accumulateCartesianDerivatives() from LJAnalyticalDerivatives.cuh
 * which converts r-derivatives to Cartesian derivatives.
 */

#ifndef HCT_CHAIN_RULE_CUH
#define HCT_CHAIN_RULE_CUH

// CUDA math functions (logf, powf, fabsf, sqrtf) are built-in

/*
 * Compute HCT r-derivatives for Case 1: l = 1/R_probe
 *
 * This case occurs when |r - S| < R_probe (inside crossover region).
 * Here l = 1/R_probe is constant, so dl/dr = 0.
 *
 * @param r           Distance from receptor atom to grid point
 * @param S           Scaled receptor radius (R_j_off * scale_j)
 * @param R_probe     Probe offset radius
 * @param I           Output: [I, dI/dr, d²I/dr², ..., d⁶I/dr⁶]
 */
__device__ __forceinline__ void computeHCT_rDerivs_case1(
    float r, float S, float R_probe, float I[7])
{
    // Precompute common terms
    float rps = r + S;

    float inv_r = 1.0f / r;
    float inv_rps = 1.0f / rps;
    float inv_Rp = 1.0f / R_probe;

    // Powers of common terms
    float inv_r2 = inv_r * inv_r;
    float inv_r3 = inv_r2 * inv_r;
    float inv_r4 = inv_r3 * inv_r;
    float inv_r5 = inv_r4 * inv_r;
    float inv_r6 = inv_r5 * inv_r;
    float inv_r7 = inv_r6 * inv_r;

    float inv_rps2 = inv_rps * inv_rps;
    float inv_rps3 = inv_rps2 * inv_rps;
    float inv_rps4 = inv_rps3 * inv_rps;
    float inv_rps5 = inv_rps4 * inv_rps;
    float inv_rps6 = inv_rps5 * inv_rps;
    float inv_rps7 = inv_rps6 * inv_rps;
    float inv_rps8 = inv_rps7 * inv_rps;

    float inv_Rp2 = inv_Rp * inv_Rp;

    float S2 = S * S;

    // log(R_probe/(r+S))
    float log_ratio = logf(R_probe * inv_rps);

    // r-derivatives

    // Common subexpressions
    float t0 = S + r;
    float t1 = (1.0f / (t0));
    float t2 = (1.0f / (r));
    float t3 = (R_probe * R_probe);
    float t4 = (1.0f / (t3));
    float t5 = -t4 + (1.0f / (t0 * t0));
    float t6 = (S * S);
    float t7 = (r * r);
    float t8 = 2.0f*S;
    float t9 = r*t8 + t6 + t7;
    float t10 = 2.0f*t3;
    float t11 = t10*t9;
    float t12 = (r * r * r);
    float t13 = (S * S * S);
    float t14 = r*t13;
    float t15 = t6*t7;
    float t16 = (S * S * S * S);
    float t17 = (r * r * r * r);
    float t18 = t16 + t17;
    float t19 = 3.0f*t7;
    float t20 = 3.0f*r;
    float t21 = S*t19 + t12 + t13 + t20*t6;
    float t22 = (S * S * S * S * S);
    float t23 = t12*t6;
    float t24 = t13*t3;
    float t25 = t3*t7;
    float t26 = t3*t6;
    float t27 = t10*t21;
    float t28 = ((0.5f))*t4;
    float t29 = S*t12;
    float t30 = 4.0f*t14 + 6.0f*t15 + t18 + 4.0f*t29;
    float t31 = (S * S * S * S * S * S);
    float t32 = r*t22;
    float t33 = t17*t6;
    float t34 = t12*t13;
    float t35 = t16*t7;
    float t36 = 6.0f*t3;
    float t37 = t30*t36;
    float t38 = (r * r * r * r * r);
    float t39 = S*t17;
    float t40 = 5.0f*r*t16 + 10.0f*t13*t7 + t22 + 10.0f*t23 + t38 + 5.0f*t39;
    float t41 = (S * S * S * S * S * S * S);
    float t42 = t3*t38;
    float t43 = 6.0f*t38;
    float t44 = t13*t17;
    float t45 = t12*t16;
    float t46 = t22*t7;
    float t47 = 47.0f*t3;
    float t48 = t16*t3;
    float t49 = 12.0f*t3*t40;
    float t50 = (r * r * r * r * r * r);
    float t51 = S*t43 + t31 + 6.0f*t32 + 15.0f*t33 + 20.0f*t34 + 15.0f*t35 + t50;
    float t52 = (S * S * S * S * S * S * S * S);
    float t53 = 30.0f*t6;
    float t54 = 60.0f*t3;
    float t55 = t51*t54;
    float t56 = (r * r * r * r * r * r * r);
    float t57 = S*t50;
    float t58 = r*t31;
    float t59 = 21.0f*t38*t6 + t41 + 35.0f*t44 + 35.0f*t45 + 21.0f*t46 + t56 + 7.0f*t57 + 7.0f*t58;
    float t60 = t54*t59;

    I[0] = ((0.25f))*r*t5 - t1 - (0.25f)*t2*t5*t6 + ((0.5f))*t2*(logf(t1) + logf(R_probe)) + (1.0f / (R_probe));
    I[1] = ((0.25f))*t4*(-t12*t8 - 2.0f*t14 - 2.0f*t15 - t18 + t3*t6 + t3*t7 + ((t11 * logf(t0)) + (-t11 * logf(R_probe))))/(t7*t9);
    I[2] = t28*(-r*t26 + t13*t19 + t16*t20 + t22 + t23 - t24 + t25*t8 + ((-t27 * logf(t0)) + (t27 * logf(R_probe))))/(t12*t21);
    I[3] = t28*(6.0f*r*t13*t3 - t10*t17 + 3.0f*t16*t3 - t19*t26 - 14.0f*t29*t3 - 3.0f*t31 - 12.0f*t32 - 3.0f*t33 - 12.0f*t34 - 18.0f*t35 + ((t37 * logf(t0)) + (-t37 * logf(R_probe))))/(t17*t30);
    I[4] = t4*(30.0f*r*t31 - 18.0f*r*t48 + 34.0f*t12*t26 - 6.0f*t13*t25 - t22*t36 + t39*t47 + 6.0f*t41 + 7.0f*t42 + t43*t6 + 30.0f*t44 + 60.0f*t45 + 60.0f*t46 + ((-t49 * logf(t0)) + (t49 * logf(R_probe))))/(t38*t40);
    I[5] = t4*(-342.0f*S*t42 + 120.0f*r*t22*t3 - 180.0f*r*t41 - 600.0f*t12*t22 - 140.0f*t12*t24 - 180.0f*t13*t38 - 450.0f*t16*t17 + 120.0f*t16*t3*t7 - 405.0f*t17*t26 + 30.0f*t3*t31 - 450.0f*t31*t7 - t47*t50 - t50*t53 - 30.0f*t52 + ((t55 * logf(t0)) + (-t55 * logf(R_probe))))/(t50*t51);
    I[6] = 6.0f*t4*(30.0f*powf(S, 9.0f) + 210.0f*r*t52 + 1050.0f*t12*t31 + 20.0f*t12*t48 + 210.0f*t13*t50 + 630.0f*t16*t38 + 1050.0f*t17*t22 + 545.0f*t17*t24 - 240.0f*t22*t25 + 747.0f*t26*t38 - 30.0f*t3*t41 + 57.0f*t3*t56 + 459.0f*t3*t57 - 150.0f*t3*t58 + 630.0f*t41*t7 + t53*t56 + ((-t60 * logf(t0)) + (t60 * logf(R_probe))))/(t56*t59);
}

/*
 * Compute HCT r-derivatives for Case 2: l = 1/(r-S)
 *
 * This case occurs when |r - S| >= R_probe (outside crossover region).
 * Here l = 1/(r-S), so dl/dr = -1/(r-S)^2.
 *
 * @param r           Distance from receptor atom to grid point
 * @param S           Scaled receptor radius (R_j_off * scale_j)
 * @param R_probe     Probe offset radius
 * @param I           Output: [I, dI/dr, d²I/dr², ..., d⁶I/dr⁶]
 */
__device__ __forceinline__ void computeHCT_rDerivs_case2(
    float r, float S, float R_probe, float I[7])
{
    // Precompute common terms
    float rps = r + S;
    float rms = r - S;

    float inv_r = 1.0f / r;
    float inv_rps = 1.0f / rps;
    float inv_rms = 1.0f / rms;

    // Powers of common terms
    float inv_r2 = inv_r * inv_r;
    float inv_r3 = inv_r2 * inv_r;
    float inv_r4 = inv_r3 * inv_r;
    float inv_r5 = inv_r4 * inv_r;
    float inv_r6 = inv_r5 * inv_r;
    float inv_r7 = inv_r6 * inv_r;

    float inv_rps2 = inv_rps * inv_rps;
    float inv_rps3 = inv_rps2 * inv_rps;
    float inv_rps4 = inv_rps3 * inv_rps;
    float inv_rps5 = inv_rps4 * inv_rps;
    float inv_rps6 = inv_rps5 * inv_rps;
    float inv_rps7 = inv_rps6 * inv_rps;
    float inv_rps8 = inv_rps7 * inv_rps;

    float inv_rms2 = inv_rms * inv_rms;
    float inv_rms3 = inv_rms2 * inv_rms;
    float inv_rms4 = inv_rms3 * inv_rms;
    float inv_rms5 = inv_rms4 * inv_rms;
    float inv_rms6 = inv_rms5 * inv_rms;
    float inv_rms7 = inv_rms6 * inv_rms;
    float inv_rms8 = inv_rms7 * inv_rms;

    float S2 = S * S;

    // log((r-S)/(r+S))
    float log_ratio = logf(rms * inv_rps);

    // r-derivatives

    // Common subexpressions
    float t0 = -S + r;
    float t1 = S + r;
    float t2 = (1.0f / (t1));
    float t3 = (1.0f / (r));
    float t4 = (1.0f / (t1 * t1)) - 1.0f/(t0 * t0);
    float t5 = (S * S);
    float t6 = (r * r);
    float t7 = (S * S * S * S);
    float t8 = (r * r * r * r);
    float t9 = -2.0f*t5*t6 + t7 + t8;
    float t10 = (r * r * r);
    float t11 = 2.0f*S;
    float t12 = (S * S * S);
    float t13 = 2.0f*r;
    float t14 = logf(t0);
    float t15 = t14*t7;
    float t16 = t14*t8;
    float t17 = (S * S * S * S * S * S);
    float t18 = (r * r * r * r * r * r);
    float t19 = 3.0f*t5;
    float t20 = t17 - t18 + t19*t8 - 3.0f*t6*t7;
    float t21 = (r * r * r * r * r);
    float t22 = (S * S * S * S * S);
    float t23 = t14*t18;
    float t24 = t14*t17;
    float t25 = (S * S * S * S * S * S * S * S);
    float t26 = (r * r * r * r * r * r * r * r);
    float t27 = t18*t5;
    float t28 = t7*t8;
    float t29 = t17*t6;
    float t30 = (r * r * r * r * r * r * r);
    float t31 = 6.0f*S;
    float t32 = (S * S * S * S * S * S * S);
    float t33 = 6.0f*r;
    float t34 = 3.0f*t25;
    float t35 = 3.0f*t26;
    float t36 = powf(S, 10.0f);
    float t37 = powf(r, 10.0f);
    float t38 = t26*t5;
    float t39 = t17*t8;
    float t40 = powf(r, 9.0f);
    float t41 = powf(S, 9.0f);
    float t42 = 3.0f*t36;
    float t43 = 3.0f*t37;
    float t44 = 15.0f*t38;
    float t45 = 15.0f*t25*t6;
    float t46 = powf(S, 12.0f);
    float t47 = powf(r, 12.0f);
    float t48 = t37*t5;
    float t49 = t26*t7;
    float t50 = t17*t18;
    float t51 = t25*t8;
    float t52 = t36*t6;
    float t53 = powf(r, 11.0f);
    float t54 = 30.0f*S;
    float t55 = powf(S, 11.0f);
    float t56 = 30.0f*r;
    float t57 = 15.0f*t46;
    float t58 = 15.0f*t47;
    float t59 = powf(S, 14.0f);
    float t60 = powf(r, 14.0f);
    float t61 = t47*t5;
    float t62 = t17*t26;
    float t63 = t36*t8;
    float t64 = 15.0f*t59;
    float t65 = 15.0f*t60;
    float t66 = 105.0f*t61;
    float t67 = 105.0f*t46*t6;

    I[0] = ((0.25f))*r*t4 - t2 - (0.25f)*t3*t4*t5 + ((0.5f))*t3*(logf(t0) + logf(t2)) + (1.0f / (t0));
    I[1] = ((0.5f))*(-t10*t11 - t12*t13 + 2.0f*t14*t5*t6 - t15 - t16 + (t9 * logf(t1)))/(t6*t9);
    I[2] = -(8.0f*t10*t12 + t11*t21 - t13*t22 + 3.0f*t15*t6 - t16*t19 + t23 - t24 + (t20 * logf(t1)))/(t10*t20);
    I[3] = (22.0f*t10*t22 - 58.0f*t12*t21 + 12.0f*t14*t17*t6 + 12.0f*t14*t18*t5 - t14*t34 - t14*t35 - 18.0f*t15*t8 - t30*t31 - t32*t33 + (-12.0f*t27 + 18.0f*t28 - 12.0f*t29 + t34 + t35 * logf(t1)))/(t8*(t25 + t26 - 4.0f*t27 + 6.0f*t28 - 4.0f*t29));
    I[4] = 4.0f*(28.0f*t10*t32 + 112.0f*t12*t30 - t14*t42 + t14*t43 - t14*t44 + t14*t45 + 30.0f*t15*t18 - 30.0f*t16*t17 - 44.0f*t21*t22 + t31*t40 - t33*t41 + (-30.0f*t18*t7 + 30.0f*t39 + t42 - t43 + t44 - t45 * logf(t1)))/(t21*(10.0f*t18*t7 + 5.0f*t25*t6 - t36 + t37 - 5.0f*t38 - 10.0f*t39));
    I[5] = 4.0f*(170.0f*t10*t41 - 950.0f*t12*t40 + 300.0f*t14*t17*t18 + 90.0f*t14*t36*t6 + 90.0f*t14*t37*t5 - t14*t57 - t14*t58 - 225.0f*t15*t26 - 225.0f*t16*t25 - 396.0f*t21*t32 + 276.0f*t22*t30 - t53*t54 - t55*t56 + (-90.0f*t48 + 225.0f*t49 - 300.0f*t50 + 225.0f*t51 - 90.0f*t52 + t57 + t58 * logf(t1)))/(t18*(t46 + t47 - 6.0f*t48 + 15.0f*t49 - 20.0f*t50 + 15.0f*t51 - 6.0f*t52));
    I[6] = 24.0f*(-powf(S, 13.0f)*t56 + powf(r, 13.0f)*t54 + 200.0f*t10*t55 + 1480.0f*t12*t53 - t14*t64 + t14*t65 - t14*t66 + t14*t67 + 315.0f*t15*t37 - 315.0f*t16*t36 - 566.0f*t21*t41 - 106.0f*t22*t40 + 525.0f*t23*t25 - 525.0f*t24*t26 + 912.0f*t30*t32 + (-525.0f*t18*t25 - 315.0f*t37*t7 + 525.0f*t62 + 315.0f*t63 + t64 - t65 + t66 - t67 * logf(t1)))/(t30*(35.0f*t18*t25 + 21.0f*t37*t7 + 7.0f*t46*t6 - t59 + t60 - 7.0f*t61 - 35.0f*t62 - 21.0f*t63));
}

/*
 * Compute HCT r-derivatives, automatically selecting Case 1 or Case 2.
 *
 * @param r              Distance from receptor atom to grid point
 * @param S              Scaled receptor radius (R_j_off * scale_j)
 * @param R_probe        Probe offset radius
 * @param radial_derivs  Output: 7 r-derivatives [I, dI/dr, ..., d⁶I/dr⁶]
 */
__device__ __forceinline__ void computeHCT_rDerivs(
    float r, float S, float R_probe, float radial_derivs[7])
{
    // Crossover distance determines which formula to use
    float crossover = fabsf(r - S);

    if (R_probe > crossover) {
        // Case 1: inside crossover region (|r-S| < R_probe)
        computeHCT_rDerivs_case1(r, S, R_probe, radial_derivs);
    } else {
        // Case 2: outside crossover region (|r-S| >= R_probe)
        computeHCT_rDerivs_case2(r, S, R_probe, radial_derivs);
    }
}

#endif // HCT_CHAIN_RULE_CUH