/**
 * Inverse power transformation chain rule for analytical derivatives.
 * Auto-generated by generate_invpower_chain_rule.py
 *
 * Applies chain rule for V = U^p to transform all 27 derivatives.
 * Usage: applyInvPowerChainRule(U_derivs, p, V_derivs)
 */

#ifndef OPENMM_GRIDFORCE_INVPOWER_CHAIN_RULE_H_
#define OPENMM_GRIDFORCE_INVPOWER_CHAIN_RULE_H_

__device__ inline void applyInvPowerChainRule(
    const float U_derivs[27],  // Input: derivatives of U
    float p,                   // Power parameter (1/invPower)
    float V_derivs[27]         // Output: derivatives of V = U^p
) {
    // Extract U and its derivatives for readability
    float U = U_derivs[0];
    if (U < 1e-10f) U = 1e-10f;  // Avoid numerical issues

    float dUdx = U_derivs[1];
    float dUdy = U_derivs[2];
    float dUdz = U_derivs[3];

    float d2Udxx = U_derivs[4];
    float d2Udxy = U_derivs[5];
    float d2Udxz = U_derivs[6];
    float d2Udyy = U_derivs[7];
    float d2Udyz = U_derivs[8];
    float d2Udzz = U_derivs[9];

    float d3Uxxy = U_derivs[10];
    float d3Uxxz = U_derivs[11];
    float d3Uxyy = U_derivs[12];
    float d3Uxyz = U_derivs[13];
    float d3Uyyz = U_derivs[14];
    float d3Uxzz = U_derivs[15];
    float d3Uyzz = U_derivs[16];

    // Precompute powers of U
    float U_p = powf(U, p);
    float U_pm1 = powf(U, p - 1.0f);
    float U_pm2 = powf(U, p - 2.0f);
    float U_pm3 = powf(U, p - 3.0f);
    float U_pm4 = powf(U, p - 4.0f);
    float U_pm5 = powf(U, p - 5.0f);
    float U_pm6 = powf(U, p - 6.0f);

    // 0: Energy
    V_derivs[0] = U_p;

    // 1-3: First derivatives
    V_derivs[1] = 0;
    V_derivs[2] = 0;
    V_derivs[3] = 0;

    // 4-9: Second derivatives
    V_derivs[4] = 0;
    V_derivs[5] = 0;
    V_derivs[6] = 0;
    V_derivs[7] = 0;
    V_derivs[8] = 0;
    V_derivs[9] = 0;

    // 10-16: Third derivatives
    // Using exact formula: ∂³V = p*(p-1)*(p-2)*U^(p-3)*(∂U)³ + mixed terms + p*U^(p-1)*∂³U
    float f3_1 = p * (p - 1.0f) * (p - 2.0f) * U_pm3;
    float f3_2 = p * (p - 1.0f) * U_pm2;
    float f3_3 = p * U_pm1;

    V_derivs[10] = f3_1*dUdx*dUdx*dUdy + f3_2*(2.0f*dUdx*d2Udxy + dUdy*d2Udxx) + f3_3*d3Uxxy;
    V_derivs[11] = f3_1*dUdx*dUdx*dUdz + f3_2*(2.0f*dUdx*d2Udxz + dUdz*d2Udxx) + f3_3*d3Uxxz;
    V_derivs[12] = f3_1*dUdx*dUdy*dUdy + f3_2*(dUdx*d2Udyy + 2.0f*dUdy*d2Udxy) + f3_3*d3Uxyy;
    V_derivs[13] = f3_1*dUdx*dUdy*dUdz + f3_2*(dUdx*d2Udyz + dUdy*d2Udxz + dUdz*d2Udxy) + f3_3*d3Uxyz;
    V_derivs[14] = f3_1*dUdy*dUdy*dUdz + f3_2*(2.0f*dUdy*d2Udyz + dUdz*d2Udyy) + f3_3*d3Uyyz;
    V_derivs[15] = f3_1*dUdx*dUdz*dUdz + f3_2*(dUdx*d2Udzz + 2.0f*dUdz*d2Udxz) + f3_3*d3Uxzz;
    V_derivs[16] = f3_1*dUdy*dUdz*dUdz + f3_2*(dUdy*d2Udzz + 2.0f*dUdz*d2Udyz) + f3_3*d3Uyzz;

    // 17-26: Fourth, fifth, and sixth derivatives
    // Using exact Faà di Bruno formula
    float f4_1 = p * (p - 1.0f) * (p - 2.0f) * (p - 3.0f) * U_pm4;
    float f4_2 = p * (p - 1.0f) * (p - 2.0f) * U_pm3;
    float f4_3 = p * (p - 1.0f) * U_pm2;
    float f4_4 = p * U_pm1;

    // ∂⁴V/∂x²∂y² (index 17)
    V_derivs[17] = f4_1*dUdx*dUdx*dUdy*dUdy
                 + f4_2*(dUdx*dUdx*d2Udyy + 4.0f*dUdx*dUdy*d2Udxy + dUdy*dUdy*d2Udxx)
                 + f4_3*(d2Udxx*d2Udyy + 2.0f*d2Udxy*d2Udxy)
                 + f4_4*U_derivs[17];  // ∂⁴U/∂x²∂y²

    // ∂⁴V/∂x²∂z² (index 18)
    V_derivs[18] = f4_1*dUdx*dUdx*dUdz*dUdz
                 + f4_2*(dUdx*dUdx*d2Udzz + 4.0f*dUdx*dUdz*d2Udxz + dUdz*dUdz*d2Udxx)
                 + f4_3*(d2Udxx*d2Udzz + 2.0f*d2Udxz*d2Udxz)
                 + f4_4*U_derivs[18];  // ∂⁴U/∂x²∂z²

    // ∂⁴V/∂y²∂z² (index 19)
    V_derivs[19] = f4_1*dUdy*dUdy*dUdz*dUdz
                 + f4_2*(dUdy*dUdy*d2Udzz + 4.0f*dUdy*dUdz*d2Udyz + dUdz*dUdz*d2Udyy)
                 + f4_3*(d2Udyy*d2Udzz + 2.0f*d2Udyz*d2Udyz)
                 + f4_4*U_derivs[19];  // ∂⁴U/∂y²∂z²

    // ∂⁴V/∂x²∂y∂z (index 20)
    V_derivs[20] = f4_1*dUdx*dUdx*dUdy*dUdz
                 + f4_2*(dUdx*dUdx*d2Udyz + 2.0f*dUdx*dUdy*d2Udxz + 2.0f*dUdx*dUdz*d2Udxy + dUdy*dUdz*d2Udxx)
                 + f4_3*(d2Udxx*d2Udyz + 2.0f*d2Udxy*d2Udxz)
                 + f4_4*U_derivs[20];  // ∂⁴U/∂x²∂y∂z

    // ∂⁴V/∂x∂y²∂z (index 21)
    V_derivs[21] = f4_1*dUdx*dUdy*dUdy*dUdz
                 + f4_2*(dUdy*dUdy*d2Udxz + 2.0f*dUdx*dUdy*d2Udyz + 2.0f*dUdy*dUdz*d2Udxy + dUdx*dUdz*d2Udyy)
                 + f4_3*(d2Udyy*d2Udxz + 2.0f*d2Udxy*d2Udyz)
                 + f4_4*U_derivs[21];  // ∂⁴U/∂x∂y²∂z

    // ∂⁴V/∂x∂y∂z² (index 22)
    V_derivs[22] = f4_1*dUdx*dUdy*dUdz*dUdz
                 + f4_2*(dUdz*dUdz*d2Udxy + 2.0f*dUdx*dUdz*d2Udyz + 2.0f*dUdy*dUdz*d2Udxz + dUdx*dUdy*d2Udzz)
                 + f4_3*(d2Udzz*d2Udxy + 2.0f*d2Udxz*d2Udyz)
                 + f4_4*U_derivs[22];  // ∂⁴U/∂x∂y∂z²

    // 23-25: Fifth derivatives
    float f5_1 = p * (p - 1.0f) * (p - 2.0f) * (p - 3.0f) * (p - 4.0f) * U_pm5;
    float f5_2 = p * (p - 1.0f) * (p - 2.0f) * (p - 3.0f) * U_pm4;
    float f5_3 = p * (p - 1.0f) * (p - 2.0f) * U_pm3;
    float f5_4 = p * (p - 1.0f) * U_pm2;
    float f5_5 = p * U_pm1;

    // ∂⁵V/∂x²∂y²∂z (index 23) - simplified formula
    V_derivs[23] = f5_1*dUdx*dUdx*dUdy*dUdy*dUdz
                 + f5_3*(d2Udxx*d2Udyy*dUdz + d2Udxx*d2Udyz*dUdy + d2Udyy*d2Udxz*dUdx + 4.0f*d2Udxy*d2Udxy*dUdz + 4.0f*d2Udxy*d2Udyz*dUdx + 4.0f*d2Udxy*d2Udxz*dUdy)
                 + f5_5*U_derivs[23];  // ∂⁵U/∂x²∂y²∂z

    // ∂⁵V/∂x²∂y∂z² (index 24) - simplified formula
    V_derivs[24] = f5_1*dUdx*dUdx*dUdy*dUdz*dUdz
                 + f5_3*(d2Udxx*d2Udzz*dUdy + d2Udxx*d2Udyz*dUdz + d2Udzz*d2Udxy*dUdx + 4.0f*d2Udxz*d2Udxz*dUdy + 4.0f*d2Udxz*d2Udyz*dUdx + 4.0f*d2Udxz*d2Udxy*dUdz)
                 + f5_5*U_derivs[24];  // ∂⁵U/∂x²∂y∂z²

    // ∂⁵V/∂x∂y²∂z² (index 25) - simplified formula
    V_derivs[25] = f5_1*dUdx*dUdy*dUdy*dUdz*dUdz
                 + f5_3*(d2Udyy*d2Udzz*dUdx + d2Udyy*d2Udxz*dUdz + d2Udzz*d2Udxy*dUdy + 4.0f*d2Udyz*d2Udyz*dUdx + 4.0f*d2Udyz*d2Udxz*dUdy + 4.0f*d2Udyz*d2Udxy*dUdz)
                 + f5_5*U_derivs[25];  // ∂⁵U/∂x∂y²∂z²

    // 26: Sixth derivative ∂⁶V/∂x²∂y²∂z²
    float f6_1 = p * (p - 1.0f) * (p - 2.0f) * (p - 3.0f) * (p - 4.0f) * (p - 5.0f) * U_pm6;
    float f6_3 = p * (p - 1.0f) * (p - 2.0f) * (p - 3.0f) * U_pm4;
    float f6_4 = p * (p - 1.0f) * (p - 2.0f) * U_pm3;
    float f6_6 = p * U_pm1;

    // Simplified 6th derivative formula
    V_derivs[26] = f6_1*dUdx*dUdx*dUdy*dUdy*dUdz*dUdz
                 + f6_4*(d2Udxx*d2Udyy*d2Udzz + 8.0f*d2Udxy*d2Udxy*d2Udzz + 8.0f*d2Udxz*d2Udxz*d2Udyy + 8.0f*d2Udyz*d2Udyz*d2Udxx + 16.0f*d2Udxy*d2Udxz*d2Udyz)
                 + f6_6*U_derivs[26];  // ∂⁶U/∂x²∂y²∂z²
}

#endif  // OPENMM_GRIDFORCE_INVPOWER_CHAIN_RULE_H_
