/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_kde_chain_rule.py
 *
 * KDE chain rule for desolvation grid generation.
 * Computes all 27 RASPA3 derivatives for triquintic interpolation.
 */

#ifndef KDE_CHAIN_RULE_CUH
#define KDE_CHAIN_RULE_CUH

/*
 * Compute sigmoid and its derivatives up to 6th order.
 * S[k] = d^k(sigmoid(u))/du^k
 */
__device__ __forceinline__ void computeSigmoidDerivatives(float u, float S[7]) {
    // Numerically stable sigmoid
    float s;
    if (u >= 0.0f) {
        float e = expf(-u);
        s = 1.0f / (1.0f + e);
    } else {
        float e = expf(u);
        s = e / (1.0f + e);
    }

    float s1 = 1.0f - s;
    float base = s * s1;  // s(1-s)

    float s2 = s * s;
    float s3 = s2 * s;
    float s4 = s2 * s2;
    float s5 = s4 * s;

    S[0] = s;
    S[1] = base;
    S[2] = base * (1.0f - 2.0f*s);
    S[3] = base * (1.0f - 6.0f*s + 6.0f*s2);
    S[4] = base * (1.0f - 14.0f*s + 36.0f*s2 - 24.0f*s3);
    S[5] = base * (1.0f - 30.0f*s + 150.0f*s2 - 240.0f*s3 + 120.0f*s4);
    S[6] = base * (1.0f - 62.0f*s + 540.0f*s2 - 1560.0f*s3 + 1800.0f*s4 - 720.0f*s5);
}

/*
 * Compute r-derivatives of KDE weight: w = sig1 * sig2
 *
 * CORRECTED formula that matches binned approach:
 *   crossover = |r - S|
 *   u1 = (threshold - crossover) / bandwidth
 *   u2 = (R_probe - crossover) / bandwidth
 *
 * This gives w ≈ 1 when crossover < min(threshold, R_probe) (contributing).
 * As bandwidth → 0, this converges to hard-cutoff binned approach.
 *
 * For chain rule: du/dr = -sign(r-S)/bandwidth
 * So d^k(sigmoid)/dr^k = sigmoid^(k)(u) * (-sign(r-S)/bandwidth)^k
 */
__device__ __forceinline__ void computeKDEWeightDerivatives(
    float r, float S, float threshold, float R_probe, float bandwidth,
    float W[7])
{
    // Crossover distance (absolute value)
    float crossover = fabsf(r - S);

    // Sign for chain rule: d(crossover)/dr = sign(r - S)
    float sign_r_S = (r >= S) ? 1.0f : -1.0f;

    float invB = 1.0f / bandwidth;

    // CORRECTED sigmoid arguments (inverted to match binned)
    float u1 = (threshold - crossover) * invB;
    float u2 = (R_probe - crossover) * invB;

    float S1[7], S2[7];
    computeSigmoidDerivatives(u1, S1);
    computeSigmoidDerivatives(u2, S2);

    // Chain rule factor: du/dr = -sign(r-S)/bandwidth
    // So d^k(sigmoid)/dr^k = sigmoid^(k)(u) * (-sign(r-S)/bandwidth)^k
    // The factor (-sign)^k causes sign flips on odd-order derivatives
    float chainFactor = -sign_r_S * invB;
    float chainPow[7];
    chainPow[0] = 1.0f;
    chainPow[1] = chainFactor;
    chainPow[2] = chainPow[1] * chainFactor;
    chainPow[3] = chainPow[2] * chainFactor;
    chainPow[4] = chainPow[3] * chainFactor;
    chainPow[5] = chainPow[4] * chainFactor;
    chainPow[6] = chainPow[5] * chainFactor;

    // Leibniz rule: w^(n) = sum_{k=0}^n C(n,k) sig1^(k) sig2^(n-k)
    W[0] = (S1[0]*S2[0]) * chainPow[0];
    W[1] = (S1[0]*S2[1] + S1[1]*S2[0]) * chainPow[1];
    W[2] = (S1[0]*S2[2] + 2.0f*S1[1]*S2[1] + S1[2]*S2[0]) * chainPow[2];
    W[3] = (S1[0]*S2[3] + 3.0f*S1[1]*S2[2] + 3.0f*S1[2]*S2[1] + S1[3]*S2[0]) * chainPow[3];
    W[4] = (S1[0]*S2[4] + 4.0f*S1[1]*S2[3] + 6.0f*S1[2]*S2[2] + 4.0f*S1[3]*S2[1] + S1[4]*S2[0]) * chainPow[4];
    W[5] = (S1[0]*S2[5] + 5.0f*S1[1]*S2[4] + 10.0f*S1[2]*S2[3] + 10.0f*S1[3]*S2[2] + 5.0f*S1[4]*S2[1] + S1[5]*S2[0]) * chainPow[5];
    W[6] = (S1[0]*S2[6] + 6.0f*S1[1]*S2[5] + 15.0f*S1[2]*S2[4] + 20.0f*S1[3]*S2[3] + 15.0f*S1[4]*S2[2] + 6.0f*S1[5]*S2[1] + S1[6]*S2[0]) * chainPow[6];
}

/*
 * Compute r-derivatives for N grid: f = 1
 */
__device__ __forceinline__ void computeFN_r_derivs(float r, float S, float F[7]) {
    F[0] = 1.0f;
    F[1] = F[2] = F[3] = F[4] = F[5] = F[6] = 0.0f;
}

/*
 * Compute r-derivatives for A grid: f = r - S^2/r
 */
__device__ __forceinline__ void computeFA_r_derivs(float r, float S, float F[7]) {
    float S2 = S * S;
    float invR = 1.0f / r;
    float invR2 = invR * invR;
    float invR3 = invR2 * invR;
    float invR4 = invR3 * invR;
    float invR5 = invR4 * invR;
    float invR6 = invR5 * invR;
    float invR7 = invR6 * invR;

    F[0] = r - S2 * invR;
    F[1] = 1.0f + S2 * invR2;
    F[2] = -2.0f * S2 * invR3;
    F[3] = 6.0f * S2 * invR4;
    F[4] = -24.0f * S2 * invR5;
    F[5] = 120.0f * S2 * invR6;
    F[6] = -720.0f * S2 * invR7;
}

/*
 * Compute r-derivatives for B grid: f = 0.5 / sqrt(r^2 + eps^2)
 */
__device__ __forceinline__ void computeFB_r_derivs(float r, float epsilon_B, float F[7]) {
    float r2 = r * r;
    float e2 = epsilon_B * epsilon_B;
    float rho2 = r2 + e2;
    float rho = sqrtf(rho2);

    float invRho = 1.0f / rho;
    float invRho3 = invRho / rho2;
    float invRho5 = invRho3 / rho2;
    float invRho7 = invRho5 / rho2;
    float invRho9 = invRho7 / rho2;
    float invRho11 = invRho9 / rho2;
    float invRho13 = invRho11 / rho2;

    float r3 = r2 * r;
    float r4 = r2 * r2;
    float r5 = r4 * r;
    float r6 = r3 * r3;

    F[0] = 0.5f * invRho;
    F[1] = -0.5f * r * invRho3;
    F[2] = 0.5f * (-invRho3 + 3.0f*r2*invRho5);
    F[3] = 0.5f * (9.0f*r*invRho5 - 15.0f*r3*invRho7);
    F[4] = 0.5f * (9.0f*invRho5 - 90.0f*r2*invRho7 + 105.0f*r4*invRho9);
    F[5] = 0.5f * (-225.0f*r*invRho7 + 1050.0f*r3*invRho9 - 945.0f*r5*invRho11);
    F[6] = 0.5f * (-225.0f*invRho7 + 4725.0f*r2*invRho9 - 14175.0f*r4*invRho11 + 10395.0f*r6*invRho13);
}

/*
 * Compute r-derivatives of g = w * f using Leibniz rule.
 */
__device__ __forceinline__ void computeProductDerivatives(
    const float W[7], const float F[7], float G[7])
{
    G[0] = W[0]*F[0];
    G[1] = W[0]*F[1] + W[1]*F[0];
    G[2] = W[0]*F[2] + 2.0f*W[1]*F[1] + W[2]*F[0];
    G[3] = W[0]*F[3] + 3.0f*W[1]*F[2] + 3.0f*W[2]*F[1] + W[3]*F[0];
    G[4] = W[0]*F[4] + 4.0f*W[1]*F[3] + 6.0f*W[2]*F[2] + 4.0f*W[3]*F[1] + W[4]*F[0];
    G[5] = W[0]*F[5] + 5.0f*W[1]*F[4] + 10.0f*W[2]*F[3] + 10.0f*W[3]*F[2] + 5.0f*W[4]*F[1] + W[5]*F[0];
    G[6] = W[0]*F[6] + 6.0f*W[1]*F[5] + 15.0f*W[2]*F[4] + 20.0f*W[3]*F[3] + 15.0f*W[4]*F[2] + 6.0f*W[5]*F[1] + W[6]*F[0];
}

/*
 * Apply chain rule to convert r-derivatives to Cartesian derivatives.
 *
 * Input: G[0..6] = d^k(g)/dr^k, nx, ny, nz = direction cosines, r = distance
 * Output: derivs[0..26] = all 27 RASPA3 Cartesian derivatives
 */
__device__ __forceinline__ void applyChainRuleTriquintic(
    const float G[7], float nx, float ny, float nz, float r,
    float derivs[27])
{
    float G0 = G[0], G1 = G[1], G2 = G[2], G3 = G[3];
    float G4 = G[4], G5 = G[5], G6 = G[6];

    float r2 = r * r;
    float r3 = r2 * r;
    float r4 = r3 * r;
    float r5 = r4 * r;

    float nx2 = nx * nx;
    float ny2 = ny * ny;
    float nz2 = nz * nz;

    // f
    derivs[0] = G0;

    // fx
    derivs[1] = G1*nx;

    // fy
    derivs[2] = G1*ny;

    // fz
    derivs[3] = G1*nz;

    // fxx
    derivs[4] = (-G1*(nx2 - 1.0f) + G2*nx2*r)/r;

    // fxy
    derivs[5] = nx*ny*(-G1 + G2*r)/r;

    // fxz
    derivs[6] = nx*nz*(-G1 + G2*r)/r;

    // fyy
    derivs[7] = (-G1*(ny2 - 1.0f) + G2*ny2*r)/r;

    // fyz
    derivs[8] = ny*nz*(-G1 + G2*r)/r;

    // fzz
    derivs[9] = (-G1*(nz2 - 1.0f) + G2*nz2*r)/r;

    // fxxy
    derivs[10] = ny*(3.0f*G1*nx2 - G1 - 3.0f*G2*nx2*r + G2*r + G3*nx2*r2)/r2;

    // fxxz
    derivs[11] = nz*(3.0f*G1*nx2 - G1 - 3.0f*G2*nx2*r + G2*r + G3*nx2*r2)/r2;

    // fxyy
    derivs[12] = nx*(3.0f*G1*ny2 - G1 - 3.0f*G2*ny2*r + G2*r + G3*ny2*r2)/r2;

    // fxyz
    derivs[13] = nx*ny*nz*(3.0f*G1 - 3.0f*G2*r + G3*r2)/r2;

    // fyyz
    derivs[14] = nz*(3.0f*G1*ny2 - G1 - 3.0f*G2*ny2*r + G2*r + G3*ny2*r2)/r2;

    // fxzz
    derivs[15] = nx*(3.0f*G1*nz2 - G1 - 3.0f*G2*nz2*r + G2*r + G3*nz2*r2)/r2;

    // fyzz
    derivs[16] = ny*(3.0f*G1*nz2 - G1 - 3.0f*G2*nz2*r + G2*r + G3*nz2*r2)/r2;

    // fxxyy
    derivs[17] = (-15.0f*G1*nx2*ny2 + 3.0f*G1*nx2 + 3.0f*G1*ny2 - G1 + 15.0f*G2*nx2*ny2*r - 3.0f*G2*nx2*r - 3.0f*G2*ny2*r + G2*r - 6.0f*G3*nx2*ny2*r2 + G3*nx2*r2 + G3*ny2*r2 + G4*nx2*ny2*r3)/r3;

    // fxxzz
    derivs[18] = (-15.0f*G1*nx2*nz2 + 3.0f*G1*nx2 + 3.0f*G1*nz2 - G1 + 15.0f*G2*nx2*nz2*r - 3.0f*G2*nx2*r - 3.0f*G2*nz2*r + G2*r - 6.0f*G3*nx2*nz2*r2 + G3*nx2*r2 + G3*nz2*r2 + G4*nx2*nz2*r3)/r3;

    // fyyzz
    derivs[19] = (-15.0f*G1*ny2*nz2 + 3.0f*G1*ny2 + 3.0f*G1*nz2 - G1 + 15.0f*G2*ny2*nz2*r - 3.0f*G2*ny2*r - 3.0f*G2*nz2*r + G2*r - 6.0f*G3*ny2*nz2*r2 + G3*ny2*r2 + G3*nz2*r2 + G4*ny2*nz2*r3)/r3;

    // fxxyz
    derivs[20] = ny*nz*(-15.0f*G1*nx2 + 3.0f*G1 + 15.0f*G2*nx2*r - 3.0f*G2*r - 6.0f*G3*nx2*r2 + G3*r2 + G4*nx2*r3)/r3;

    // fxyyz
    derivs[21] = nx*nz*(-15.0f*G1*ny2 + 3.0f*G1 + 15.0f*G2*ny2*r - 3.0f*G2*r - 6.0f*G3*ny2*r2 + G3*r2 + G4*ny2*r3)/r3;

    // fxyzz
    derivs[22] = nx*ny*(-15.0f*G1*nz2 + 3.0f*G1 + 15.0f*G2*nz2*r - 3.0f*G2*r - 6.0f*G3*nz2*r2 + G3*r2 + G4*nz2*r3)/r3;

    // fxxyyz
    derivs[23] = nz*(105.0f*G1*nx2*ny2 - 15.0f*G1*nx2 - 15.0f*G1*ny2 + 3.0f*G1 - 105.0f*G2*nx2*ny2*r + 15.0f*G2*nx2*r + 15.0f*G2*ny2*r - 3.0f*G2*r + 45.0f*G3*nx2*ny2*r2 - 6.0f*G3*nx2*r2 - 6.0f*G3*ny2*r2 + G3*r2 - 10.0f*G4*nx2*ny2*r3 + G4*nx2*r3 + G4*ny2*r3 + G5*nx2*ny2*r4)/r4;

    // fxxyzz
    derivs[24] = ny*(105.0f*G1*nx2*nz2 - 15.0f*G1*nx2 - 15.0f*G1*nz2 + 3.0f*G1 - 105.0f*G2*nx2*nz2*r + 15.0f*G2*nx2*r + 15.0f*G2*nz2*r - 3.0f*G2*r + 45.0f*G3*nx2*nz2*r2 - 6.0f*G3*nx2*r2 - 6.0f*G3*nz2*r2 + G3*r2 - 10.0f*G4*nx2*nz2*r3 + G4*nx2*r3 + G4*nz2*r3 + G5*nx2*nz2*r4)/r4;

    // fxyyzz
    derivs[25] = nx*(105.0f*G1*ny2*nz2 - 15.0f*G1*ny2 - 15.0f*G1*nz2 + 3.0f*G1 - 105.0f*G2*ny2*nz2*r + 15.0f*G2*ny2*r + 15.0f*G2*nz2*r - 3.0f*G2*r + 45.0f*G3*ny2*nz2*r2 - 6.0f*G3*ny2*r2 - 6.0f*G3*nz2*r2 + G3*r2 - 10.0f*G4*ny2*nz2*r3 + G4*ny2*r3 + G4*nz2*r3 + G5*ny2*nz2*r4)/r4;

    // fxxyyzz
    derivs[26] = (-945.0f*G1*nx2*ny2*nz2 + 105.0f*G1*nx2*ny2 + 105.0f*G1*nx2*nz2 - 15.0f*G1*nx2 + 105.0f*G1*ny2*nz2 - 15.0f*G1*ny2 - 15.0f*G1*nz2 + 3.0f*G1 + 945.0f*G2*nx2*ny2*nz2*r - 105.0f*G2*nx2*ny2*r - 105.0f*G2*nx2*nz2*r + 15.0f*G2*nx2*r - 105.0f*G2*ny2*nz2*r + 15.0f*G2*ny2*r + 15.0f*G2*nz2*r - 3.0f*G2*r - 420.0f*G3*nx2*ny2*nz2*r2 + 45.0f*G3*nx2*ny2*r2 + 45.0f*G3*nx2*nz2*r2 - 6.0f*G3*nx2*r2 + 45.0f*G3*ny2*nz2*r2 - 6.0f*G3*ny2*r2 - 6.0f*G3*nz2*r2 + G3*r2 + 105.0f*G4*nx2*ny2*nz2*r3 - 10.0f*G4*nx2*ny2*r3 - 10.0f*G4*nx2*nz2*r3 + G4*nx2*r3 - 10.0f*G4*ny2*nz2*r3 + G4*ny2*r3 + G4*nz2*r3 - 15.0f*G5*nx2*ny2*nz2*r4 + G5*nx2*ny2*r4 + G5*nx2*nz2*r4 + G5*ny2*nz2*r4 + G6*nx2*ny2*nz2*r5)/r5;

}

/*
 * Compute all 27 derivatives for N grid (KDE-weighted count).
 */
__device__ __forceinline__ void computeKDEDerivs_N(
    float dx, float dy, float dz, float S,
    float threshold, float R_probe, float bandwidth,
    float derivs[27])
{
    float r2 = dx*dx + dy*dy + dz*dz;
    float r = sqrtf(r2);
    float invR = rsqrtf(r2);
    float nx = dx * invR;
    float ny = dy * invR;
    float nz = dz * invR;

    float W[7], F[7], G[7];
    computeKDEWeightDerivatives(r, S, threshold, R_probe, bandwidth, W);
    computeFN_r_derivs(r, S, F);
    computeProductDerivatives(W, F, G);
    applyChainRuleTriquintic(G, nx, ny, nz, r, derivs);
}

/*
 * Compute all 27 derivatives for A grid (r - S^2/r term).
 */
__device__ __forceinline__ void computeKDEDerivs_A(
    float dx, float dy, float dz, float S,
    float threshold, float R_probe, float bandwidth,
    float derivs[27])
{
    float r2 = dx*dx + dy*dy + dz*dz;
    float r = sqrtf(r2);
    float invR = rsqrtf(r2);
    float nx = dx * invR;
    float ny = dy * invR;
    float nz = dz * invR;

    float W[7], F[7], G[7];
    computeKDEWeightDerivatives(r, S, threshold, R_probe, bandwidth, W);
    computeFA_r_derivs(r, S, F);
    computeProductDerivatives(W, F, G);
    applyChainRuleTriquintic(G, nx, ny, nz, r, derivs);
}

/*
 * Compute all 27 derivatives for B grid (smoothed 1/r term).
 */
__device__ __forceinline__ void computeKDEDerivs_B(
    float dx, float dy, float dz, float S,
    float threshold, float R_probe, float bandwidth,
    float epsilon_B, float derivs[27])
{
    float r2 = dx*dx + dy*dy + dz*dz;
    float r = sqrtf(r2);
    float invR = rsqrtf(r2);
    float nx = dx * invR;
    float ny = dy * invR;
    float nz = dz * invR;

    float W[7], F[7], G[7];
    computeKDEWeightDerivatives(r, S, threshold, R_probe, bandwidth, W);
    computeFB_r_derivs(r, epsilon_B, F);
    computeProductDerivatives(W, F, G);
    applyChainRuleTriquintic(G, nx, ny, nz, r, derivs);
}

#endif // KDE_CHAIN_RULE_CUH