/*
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generate_tanh_chain_rule.py
 *
 * Tanh chain rule for triquintic interpolation derivatives.
 * V = U_max * tanh(U / U_max)
 */

#ifndef TANH_CHAIN_RULE_H
#define TANH_CHAIN_RULE_H

/*
 * Compute tanh derivatives Td[0..6] where Td[n] = d^n(tanh(u))/du^n
 */
template<typename T>
__device__ static inline void computeTanhDerivatives(T u, T Td[7]) {
    if (u > 20.0f) {
        Td[0] = 1.0f;
        Td[1] = Td[2] = Td[3] = Td[4] = Td[5] = Td[6] = 0.0f;
        return;
    }
    if (u < -20.0f) {
        Td[0] = -1.0f;
        Td[1] = Td[2] = Td[3] = Td[4] = Td[5] = Td[6] = 0.0f;
        return;
    }

    T t = tanh(u);
    T t2 = t * t;
    T t4 = t2 * t2;
    T s2 = 1.0f - t2;  // sech^2(u)

    Td[0] = t;
    Td[1] = s2;
    Td[2] = -2.0f * s2 * t;
    Td[3] = 2.0f * s2 * (3.0f * t2 - 1.0f);
    Td[4] = -8.0f * s2 * t * (3.0f * t2 - 2.0f);
    Td[5] = 8.0f * s2 * (15.0f * t4 - 15.0f * t2 + 2.0f);
    Td[6] = -16.0f * s2 * t * (45.0f * t4 - 60.0f * t2 + 17.0f);
}

/*
 * Apply tanh capping to all 27 derivatives using Faa di Bruno formula.
 */
template<typename T>
__device__ static inline void applyTanhChainRule(const T* raw, T U_max, T* capped) {
    // Extract raw derivatives
    const T U = raw[0];
    const T Ux = raw[1];
    const T Uy = raw[2];
    const T Uz = raw[3];
    const T Uxx = raw[4];
    const T Uxy = raw[5];
    const T Uxz = raw[6];
    const T Uyy = raw[7];
    const T Uyz = raw[8];
    const T Uzz = raw[9];
    const T Uxxy = raw[10];
    const T Uxxz = raw[11];
    const T Uxyy = raw[12];
    const T Uxyz = raw[13];
    const T Uyyz = raw[14];
    const T Uxzz = raw[15];
    const T Uyzz = raw[16];
    const T Uxxyy = raw[17];
    const T Uxxzz = raw[18];
    const T Uyyzz = raw[19];
    const T Uxxyz = raw[20];
    const T Uxyyz = raw[21];
    const T Uxyzz = raw[22];
    const T Uxxyyz = raw[23];
    const T Uxxyzz = raw[24];
    const T Uxyyzz = raw[25];
    const T Uxxyyzz = raw[26];

    T u = U / U_max;

    // Early exit for low energies
    if (u < (T)0.1) {
        for (int i = 0; i < 27; i++) capped[i] = raw[i];
        return;
    }

    // Compute tanh derivatives
    T Td[7];
    computeTanhDerivatives(u, Td);

    // g^(n)(U) = Td[n] / U_max^(n-1)
    T invU = 1.0f / U_max;
    T invU2 = invU * invU;
    T invU3 = invU2 * invU;
    T invU4 = invU3 * invU;
    T invU5 = invU4 * invU;

    T g1 = Td[1];
    T g2 = Td[2] * invU;
    T g3 = Td[3] * invU2;
    T g4 = Td[4] * invU3;
    T g5 = Td[5] * invU4;
    T g6 = Td[6] * invU5;

    // Precomputed products of first derivatives
    T Ux2 = Ux * Ux;
    T Uy2 = Uy * Uy;
    T Uz2 = Uz * Uz;
    T UxUy = Ux * Uy;
    T UxUz = Ux * Uz;
    T UyUz = Uy * Uz;
    T Ux2Uy = Ux2 * Uy;
    T Ux2Uz = Ux2 * Uz;
    T UxUy2 = Ux * Uy2;
    T UxUz2 = Ux * Uz2;
    T Uy2Uz = Uy2 * Uz;
    T UyUz2 = Uy * Uz2;
    T UxUyUz = Ux * UyUz;
    T Ux2Uy2 = Ux2 * Uy2;
    T Ux2Uz2 = Ux2 * Uz2;
    T Uy2Uz2 = Uy2 * Uz2;
    T Ux2UyUz = Ux2 * UyUz;
    T UxUy2Uz = UxUy * UyUz;
    T UxUyUz2 = UxUy * Uz2;
    T Ux2Uy2Uz = Ux2Uy2 * Uz;
    T Ux2UyUz2 = Ux2 * UyUz2;
    T UxUy2Uz2 = Ux * Uy2Uz2;
    T Ux2Uy2Uz2 = Ux2Uy2 * Uz2;

    // Apply Faa di Bruno chain rule
    // Index 0: V
    capped[0] = U_max * Td[0];

    // Index 1: Vx
    capped[1] = g1 * Ux;

    // Index 2: Vy
    capped[2] = g1 * Uy;

    // Index 3: Vz
    capped[3] = g1 * Uz;

    // Index 4: Vxx
    capped[4] = g1 * Uxx + g2 * Ux2;

    // Index 5: Vxy
    capped[5] = g1 * Uxy + g2 * UxUy;

    // Index 6: Vxz
    capped[6] = g1 * Uxz + g2 * UxUz;

    // Index 7: Vyy
    capped[7] = g1 * Uyy + g2 * Uy2;

    // Index 8: Vyz
    capped[8] = g1 * Uyz + g2 * UyUz;

    // Index 9: Vzz
    capped[9] = g1 * Uzz + g2 * Uz2;

    // Index 10: Vxxy
    capped[10] = g1 * Uxxy + g2 * Uy * Uxx + 2.0f * g2 * Ux * Uxy + g3 * Ux2Uy;

    // Index 11: Vxxz
    capped[11] = g1 * Uxxz + g2 * Uz * Uxx + 2.0f * g2 * Ux * Uxz + g3 * Ux2Uz;

    // Index 12: Vxyy
    capped[12] = g1 * Uxyy + 2.0f * g2 * Uy * Uxy + g2 * Ux * Uyy + g3 * UxUy2;

    // Index 13: Vxyz
    capped[13] =
        g1 * Uxyz
        + g2 * Uz * Uxy
        + g2 * Uy * Uxz
        + g2 * Ux * Uyz
        + g3 * UxUyUz;

    // Index 14: Vyyz
    capped[14] = g1 * Uyyz + g2 * Uz * Uyy + 2.0f * g2 * Uy * Uyz + g3 * Uy2Uz;

    // Index 15: Vxzz
    capped[15] = g1 * Uxzz + 2.0f * g2 * Uz * Uxz + g2 * Ux * Uzz + g3 * UxUz2;

    // Index 16: Vyzz
    capped[16] = g1 * Uyzz + 2.0f * g2 * Uz * Uyz + g2 * Uy * Uzz + g3 * UyUz2;

    // Index 17: Vxxyy
    capped[17] =
        g1 * Uxxyy
        + 2.0f * g2 * Uy * Uxxy
        + g2 * Uyy * Uxx
        + 2.0f * g2 * Ux * Uxyy
        + 2.0f * g2 * Uxy * Uxy
        + g3 * Uy2 * Uxx
        + 4.0f * g3 * UxUy * Uxy
        + g3 * Ux2 * Uyy
        + g4 * Ux2Uy2;

    // Index 18: Vxxzz
    capped[18] =
        g1 * Uxxzz
        + 2.0f * g2 * Uz * Uxxz
        + g2 * Uzz * Uxx
        + 2.0f * g2 * Ux * Uxzz
        + 2.0f * g2 * Uxz * Uxz
        + g3 * Uz2 * Uxx
        + 4.0f * g3 * UxUz * Uxz
        + g3 * Ux2 * Uzz
        + g4 * Ux2Uz2;

    // Index 19: Vyyzz
    capped[19] =
        g1 * Uyyzz
        + 2.0f * g2 * Uz * Uyyz
        + g2 * Uzz * Uyy
        + 2.0f * g2 * Uy * Uyzz
        + 2.0f * g2 * Uyz * Uyz
        + g3 * Uz2 * Uyy
        + 4.0f * g3 * UyUz * Uyz
        + g3 * Uy2 * Uzz
        + g4 * Uy2Uz2;

    // Index 20: Vxxyz
    capped[20] =
        g1 * Uxxyz
        + g2 * Uz * Uxxy
        + g2 * Uy * Uxxz
        + g2 * Uyz * Uxx
        + 2.0f * g2 * Ux * Uxyz
        + 2.0f * g2 * Uxz * Uxy
        + g3 * UyUz * Uxx
        + 2.0f * g3 * UxUz * Uxy
        + 2.0f * g3 * UxUy * Uxz
        + g3 * Ux2 * Uyz
        + g4 * Ux2UyUz;

    // Index 21: Vxyyz
    capped[21] =
        g1 * Uxyyz
        + g2 * Uz * Uxyy
        + 2.0f * g2 * Uy * Uxyz
        + 2.0f * g2 * Uyz * Uxy
        + g2 * Uyy * Uxz
        + g2 * Ux * Uyyz
        + 2.0f * g3 * UyUz * Uxy
        + g3 * UxUz * Uyy
        + g3 * Uy2 * Uxz
        + 2.0f * g3 * UxUy * Uyz
        + g4 * UxUy2Uz;

    // Index 22: Vxyzz
    capped[22] =
        g1 * Uxyzz
        + 2.0f * g2 * Uz * Uxyz
        + g2 * Uzz * Uxy
        + g2 * Uy * Uxzz
        + 2.0f * g2 * Uyz * Uxz
        + g2 * Ux * Uyzz
        + g3 * Uz2 * Uxy
        + 2.0f * g3 * UyUz * Uxz
        + 2.0f * g3 * UxUz * Uyz
        + g3 * UxUy * Uzz
        + g4 * UxUyUz2;

    // Index 23: Vxxyyz
    capped[23] =
        g1 * Uxxyyz
        + g2 * Uz * Uxxyy
        + 2.0f * g2 * Uy * Uxxyz
        + 2.0f * g2 * Uyz * Uxxy
        + g2 * Uyy * Uxxz
        + g2 * Uyyz * Uxx
        + 2.0f * g2 * Ux * Uxyyz
        + 2.0f * g2 * Uxz * Uxyy
        + 4.0f * g2 * Uxy * Uxyz
        + 2.0f * g3 * UyUz * Uxxy
        + g3 * Uz * Uyy * Uxx
        + 2.0f * g3 * UxUz * Uxyy
        + 2.0f * g3 * Uz * Uxy * Uxy
        + g3 * Uy2 * Uxxz
        + 2.0f * g3 * Uy * Uyz * Uxx
        + 4.0f * g3 * UxUy * Uxyz
        + 4.0f * g3 * Uy * Uxz * Uxy
        + 4.0f * g3 * Ux * Uyz * Uxy
        + 2.0f * g3 * Ux * Uyy * Uxz
        + g3 * Ux2 * Uyyz
        + g4 * Uy2Uz * Uxx
        + 4.0f * g4 * UxUyUz * Uxy
        + g4 * Ux2Uz * Uyy
        + 2.0f * g4 * UxUy2 * Uxz
        + 2.0f * g4 * Ux2Uy * Uyz
        + g5 * Ux2Uy2Uz;

    // Index 24: Vxxyzz
    capped[24] =
        g1 * Uxxyzz
        + 2.0f * g2 * Uz * Uxxyz
        + g2 * Uzz * Uxxy
        + g2 * Uy * Uxxzz
        + 2.0f * g2 * Uyz * Uxxz
        + g2 * Uyzz * Uxx
        + 2.0f * g2 * Ux * Uxyzz
        + 4.0f * g2 * Uxz * Uxyz
        + 2.0f * g2 * Uxzz * Uxy
        + g3 * Uz2 * Uxxy
        + 2.0f * g3 * UyUz * Uxxz
        + 2.0f * g3 * Uz * Uyz * Uxx
        + 4.0f * g3 * UxUz * Uxyz
        + 4.0f * g3 * Uz * Uxz * Uxy
        + g3 * Uy * Uzz * Uxx
        + 2.0f * g3 * Ux * Uzz * Uxy
        + 2.0f * g3 * UxUy * Uxzz
        + 2.0f * g3 * Uy * Uxz * Uxz
        + 4.0f * g3 * Ux * Uyz * Uxz
        + g3 * Ux2 * Uyzz
        + g4 * UyUz2 * Uxx
        + 2.0f * g4 * UxUz2 * Uxy
        + 4.0f * g4 * UxUyUz * Uxz
        + 2.0f * g4 * Ux2Uz * Uyz
        + g4 * Ux2Uy * Uzz
        + g5 * Ux2UyUz2;

    // Index 25: Vxyyzz
    capped[25] =
        g1 * Uxyyzz
        + 2.0f * g2 * Uz * Uxyyz
        + g2 * Uzz * Uxyy
        + 2.0f * g2 * Uy * Uxyzz
        + 4.0f * g2 * Uyz * Uxyz
        + 2.0f * g2 * Uyzz * Uxy
        + g2 * Uyy * Uxzz
        + 2.0f * g2 * Uyyz * Uxz
        + g2 * Ux * Uyyzz
        + g3 * Uz2 * Uxyy
        + 4.0f * g3 * UyUz * Uxyz
        + 4.0f * g3 * Uz * Uyz * Uxy
        + 2.0f * g3 * Uz * Uyy * Uxz
        + 2.0f * g3 * UxUz * Uyyz
        + 2.0f * g3 * Uy * Uzz * Uxy
        + g3 * Ux * Uzz * Uyy
        + g3 * Uy2 * Uxzz
        + 4.0f * g3 * Uy * Uyz * Uxz
        + 2.0f * g3 * UxUy * Uyzz
        + 2.0f * g3 * Ux * Uyz * Uyz
        + 2.0f * g4 * UyUz2 * Uxy
        + g4 * UxUz2 * Uyy
        + 2.0f * g4 * Uy2Uz * Uxz
        + 4.0f * g4 * UxUyUz * Uyz
        + g4 * UxUy2 * Uzz
        + g5 * UxUy2Uz2;

    // Index 26: Vxxyyzz
    capped[26] =
        g1 * Uxxyyzz
        + 2.0f * g2 * Uz * Uxxyyz
        + g2 * Uzz * Uxxyy
        + 2.0f * g2 * Uy * Uxxyzz
        + 4.0f * g2 * Uyz * Uxxyz
        + 2.0f * g2 * Uyzz * Uxxy
        + g2 * Uyy * Uxxzz
        + 2.0f * g2 * Uyyz * Uxxz
        + g2 * Uyyzz * Uxx
        + 2.0f * g2 * Ux * Uxyyzz
        + 4.0f * g2 * Uxz * Uxyyz
        + 2.0f * g2 * Uxzz * Uxyy
        + 4.0f * g2 * Uxy * Uxyzz
        + 4.0f * g2 * Uxyz * Uxyz
        + g3 * Uz2 * Uxxyy
        + 4.0f * g3 * UyUz * Uxxyz
        + 4.0f * g3 * Uz * Uyz * Uxxy
        + 2.0f * g3 * Uz * Uyy * Uxxz
        + 2.0f * g3 * Uz * Uyyz * Uxx
        + 4.0f * g3 * UxUz * Uxyyz
        + 4.0f * g3 * Uz * Uxz * Uxyy
        + 8.0f * g3 * Uz * Uxy * Uxyz
        + 2.0f * g3 * Uy * Uzz * Uxxy
        + g3 * Uzz * Uyy * Uxx
        + 2.0f * g3 * Ux * Uzz * Uxyy
        + 2.0f * g3 * Uzz * Uxy * Uxy
        + g3 * Uy2 * Uxxzz
        + 4.0f * g3 * Uy * Uyz * Uxxz
        + 2.0f * g3 * Uy * Uyzz * Uxx
        + 4.0f * g3 * UxUy * Uxyzz
        + 8.0f * g3 * Uy * Uxz * Uxyz
        + 4.0f * g3 * Uy * Uxzz * Uxy
        + 2.0f * g3 * Uyz * Uyz * Uxx
        + 8.0f * g3 * Ux * Uyz * Uxyz
        + 8.0f * g3 * Uyz * Uxz * Uxy
        + 4.0f * g3 * Ux * Uyzz * Uxy
        + 2.0f * g3 * Ux * Uyy * Uxzz
        + 2.0f * g3 * Uyy * Uxz * Uxz
        + 4.0f * g3 * Ux * Uyyz * Uxz
        + g3 * Ux2 * Uyyzz
        + 2.0f * g4 * UyUz2 * Uxxy
        + g4 * Uz2 * Uyy * Uxx
        + 2.0f * g4 * UxUz2 * Uxyy
        + 2.0f * g4 * Uz2 * Uxy * Uxy
        + 2.0f * g4 * Uy2Uz * Uxxz
        + 4.0f * g4 * UyUz * Uyz * Uxx
        + 8.0f * g4 * UxUyUz * Uxyz
        + 8.0f * g4 * UyUz * Uxz * Uxy
        + 8.0f * g4 * UxUz * Uyz * Uxy
        + 4.0f * g4 * UxUz * Uyy * Uxz
        + 2.0f * g4 * Ux2Uz * Uyyz
        + g4 * Uy2 * Uzz * Uxx
        + 4.0f * g4 * UxUy * Uzz * Uxy
        + g4 * Ux2 * Uzz * Uyy
        + 2.0f * g4 * UxUy2 * Uxzz
        + 2.0f * g4 * Uy2 * Uxz * Uxz
        + 8.0f * g4 * UxUy * Uyz * Uxz
        + 2.0f * g4 * Ux2Uy * Uyzz
        + 2.0f * g4 * Ux2 * Uyz * Uyz
        + g5 * Uy2Uz2 * Uxx
        + 4.0f * g5 * UxUyUz2 * Uxy
        + g5 * Ux2Uz2 * Uyy
        + 4.0f * g5 * UxUy2Uz * Uxz
        + 4.0f * g5 * Ux2UyUz * Uyz
        + g5 * Ux2Uy2 * Uzz
        + g6 * Ux2Uy2Uz2;

}

#endif // TANH_CHAIN_RULE_H