"""
Tests for saving auto-generated grids to files.
"""
from __future__ import print_function
import pytest
from openmm import app
import openmm as omm
from openmm import unit
import gridforceplugin
import numpy as np
import os
import tempfile


@pytest.fixture
def receptor_system():
    """Load receptor system for grid generation."""
    prmtop = app.AmberPrmtopFile('../prmtopcrd/receptor.prmtop')
    inpcrd = app.AmberInpcrdFile('../prmtopcrd/receptor.trans.inpcrd')
    system = prmtop.createSystem(nonbondedMethod=app.NoCutoff,
                                 constraints=None,
                                 implicitSolvent=None)
    return prmtop, inpcrd, system


def test_save_autogenerated_grid(receptor_system):
    """Test that auto-generated grids can be saved and reloaded."""
    prmtop, inpcrd, system = receptor_system

    # Get receptor positions and convert to nm (strip units)
    receptor_positions = inpcrd.positions.value_in_unit(unit.nanometer)
    receptor_positions = [(p[0], p[1], p[2]) for p in receptor_positions]

    # Get all receptor atoms
    receptor_atoms = list(range(prmtop.topology.getNumAtoms()))

    # Create auto-generated grid
    force = gridforceplugin.GridForce()
    nx, ny, nz = 10, 10, 10
    dx, dy, dz = 0.05, 0.05, 0.05  # nm
    force.addGridCounts(nx, ny, nz)
    force.addGridSpacing(dx, dy, dz)
    force.setGridOrigin(0.0, 0.0, 0.0)
    force.setAutoGenerateGrid(True)
    force.setGridType("charge")
    force.setReceptorAtoms(receptor_atoms)
    force.setReceptorPositionsFromLists(receptor_positions)
    force.setAutoCalculateScalingFactors(True)
    force.setScalingProperty("charge")

    system.addForce(force)

    # Create context to trigger grid generation
    integrator = omm.VerletIntegrator(1.0*unit.femtoseconds)
    platform = omm.Platform.getPlatformByName('Reference')
    context = omm.Context(system, integrator, platform)
    context.setPositions(inpcrd.positions)

    # Grid should now be generated and copied back to force
    # Test that we can save it
    with tempfile.NamedTemporaryFile(suffix='.grid', delete=False) as tmp:
        tmp_file = tmp.name

    try:
        # Save the auto-generated grid
        force.saveToFile(tmp_file)
        assert os.path.exists(tmp_file), "Grid file was not created"

        # Verify file size is reasonable
        file_size = os.path.getsize(tmp_file)
        assert file_size > 100, f"Grid file too small ({file_size} bytes)"

        # Load it back and verify
        force2 = gridforceplugin.GridForce()
        force2.loadFromFile(tmp_file)

        # Verify parameters
        counts2, spacing2, vals2, sf2 = force2.getGridParameters()

        assert list(counts2) == [nx, ny, nz], f"Counts mismatch: {counts2}"
        assert np.allclose(spacing2, [dx, dy, dz]), f"Spacing mismatch: {spacing2}"
        assert len(vals2) == nx * ny * nz, f"Value count mismatch: {len(vals2)}"

        # Verify grid origin
        ox2, oy2, oz2 = force2.getGridOrigin()
        assert np.allclose([ox2, oy2, oz2], [0.0, 0.0, 0.0]), "Origin mismatch"

        # Verify grid type
        assert force2.getGridType() == "charge", "Grid type mismatch"

        print(f"[PASS] Auto-generated grid save/load test")

    finally:
        if os.path.exists(tmp_file):
            os.unlink(tmp_file)

        if 'context' in locals():
            del context
        del integrator


def test_getGridParameters_after_autogeneration(receptor_system):
    """Test that getGridParameters() returns generated values."""
    prmtop, inpcrd, system = receptor_system

    # Get receptor data
    receptor_positions = [(p[0], p[1], p[2]) for p in inpcrd.positions.value_in_unit(unit.nanometer)]
    receptor_atoms = list(range(prmtop.topology.getNumAtoms()))

    # Create auto-generated grid
    force = gridforceplugin.GridForce()
    nx, ny, nz = 8, 8, 8
    force.addGridCounts(nx, ny, nz)
    force.addGridSpacing(0.05, 0.05, 0.05)
    force.setGridOrigin(0.0, 0.0, 0.0)
    force.setAutoGenerateGrid(True)
    force.setGridType("ljr")
    force.setReceptorAtoms(receptor_atoms)
    force.setReceptorPositionsFromLists(receptor_positions)
    force.setAutoCalculateScalingFactors(True)
    force.setScalingProperty("ljr")

    system.addForce(force)

    # Before context creation, grid values should be empty
    counts_before, spacing_before, vals_before, sf_before = force.getGridParameters()
    assert len(vals_before) == 0, "Grid values should be empty before context creation"

    # Create context to trigger generation
    integrator = omm.VerletIntegrator(1.0*unit.femtoseconds)
    platform = omm.Platform.getPlatformByName('Reference')
    context = omm.Context(system, integrator, platform)
    context.setPositions(inpcrd.positions)

    # After context creation, grid values should be populated
    counts_after, spacing_after, vals_after, sf_after = force.getGridParameters()
    assert len(vals_after) == nx * ny * nz, f"Expected {nx*ny*nz} values, got {len(vals_after)}"
    assert not all(v == 0.0 for v in vals_after), "Grid values should not all be zero"

    print(f"[PASS] getGridParameters after auto-generation test")
    print(f"       Grid value range: [{min(vals_after):.2f}, {max(vals_after):.2f}]")

    del context
    del integrator


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
