# Encode CUDA kernel files into a C++ source file.
#
# Each .cu file becomes its own static string in CudaGridForceKernelSources,
# named after the file's basename + "Kernel" (e.g. isolatedBonded.cu →
# isolatedBondedKernel). Common math/interpolation headers are emitted once
# as `commonHeaders` and call sites concatenate `commonHeaders + needed
# kernel(s)` before passing to createModule(). This makes JIT cost scale
# with the kernels a Force actually uses, not with the full bundle.

SET(HEADER_ORDER
    "InterpolationBasis.cuh"
    "HermiteBasis.cuh"
    "TricubicCoefficients.cuh"
    "TriquinticCoefficients.cuh"
    "InvPowerChainRule.cuh"
    "TanhChainRule.cuh"
    "HCTChainRule.cuh"
    "KDEChainRule.cuh"
    "LJAnalyticalDerivatives.cuh"
    "GridInterpolation.cuh"
)

SET(HEADER_SOURCE "")
FOREACH(header_name ${HEADER_ORDER})
    SET(header "${KERNELS_DIR}/include/${header_name}")
    IF(EXISTS ${header})
        FILE(READ ${header} header_content)
        STRING(REGEX REPLACE "#include \"[^\"]+\\.cuh\"\n" "" header_content "${header_content}")
        SET(HEADER_SOURCE "${HEADER_SOURCE}${header_content}\n")
    ENDIF()
ENDFOREACH()

STRING(REPLACE " " ";" KERNEL_FILE_LIST "${KERNEL_FILES}")
LIST(SORT KERNEL_FILE_LIST)

SET(KERNEL_NAMES "")
FOREACH(file ${KERNEL_FILE_LIST})
    GET_FILENAME_COMPONENT(fname ${file} NAME_WE)
    LIST(APPEND KERNEL_NAMES ${fname})
ENDFOREACH()

# ----- header -----
FILE(WRITE ${KERNELS_H}
"#ifndef OPENMM_CUDAGRIDFORCEKERNELSOURCES_H_
#define OPENMM_CUDAGRIDFORCEKERNELSOURCES_H_

// Generated by EncodeCudaFiles.cmake. Do not edit by hand.

#include <string>

namespace GridForcePlugin {

class CudaGridForceKernelSources {
public:
    /// Common math/interpolation headers. Prepend to any per-file kernel
    /// source before passing to createModule().
    static std::string commonHeaders;

")
FOREACH(kname ${KERNEL_NAMES})
    FILE(APPEND ${KERNELS_H} "    static std::string ${kname}Kernel;\n")
ENDFOREACH()
FILE(APPEND ${KERNELS_H}
"};

} // namespace GridForcePlugin

#endif /*OPENMM_CUDAGRIDFORCEKERNELSOURCES_H_*/
")

# ----- cpp -----
FILE(WRITE ${KERNELS_CPP}
"#include \"CudaGridForceKernelSources.h\"

namespace GridForcePlugin {

std::string CudaGridForceKernelSources::commonHeaders = R\"KERNELSRC(
${HEADER_SOURCE}
)KERNELSRC\";

")

FOREACH(file ${KERNEL_FILE_LIST})
    GET_FILENAME_COMPONENT(fname ${file} NAME_WE)
    FILE(READ ${file} file_source)
    STRING(REGEX REPLACE "#include \"include/[^\"]+\"\n" "" file_source "${file_source}")
    STRING(REGEX REPLACE "#include \"[^\"]+\\.cuh\"\n" "" file_source "${file_source}")

    FILE(APPEND ${KERNELS_CPP}
"std::string CudaGridForceKernelSources::${fname}Kernel = R\"KERNELSRC(
${file_source}
)KERNELSRC\";

")
ENDFOREACH()

FILE(APPEND ${KERNELS_CPP}
"} // namespace GridForcePlugin
")
